a=int(input("enter first number:"))
b=int(input("enter second number:"))

print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Floor Division:",a//b)
print("Remainder:",a%b)
print("Power:",a**b)